### ISSUE TITLE
Unbalanced delimiters do not parse and yield no error

### ISSUE THREAD

**Issue by MMagueta** [Dr-Nekoma/spatula#4]
The parser yields no error and does not parse some expressions with different unbalanced delimiters. Here are two examples:

```lisp
[defun abc [(x Integer)] : Unit 
    [if [= x 1]
        [progn 
            [print String "I love Postgresql <3"] 
            [print String "Hello :)"]]
        [progn
            [print String "I love SQL Server <3"] 
            [print String "Bye :)"]]] ; <----- Lacking a ']'
```

```lisp
[defun abc [(x Integer))] ; <----- Additional ')'
    [print Integer x]]
```

**Comment by EduardoLR10** [comment]
This was caused because the parser `fileP` was using `many`, which means that if one of the declarations fails, that is ok because the previous ones are fine or none will be also ok (remember that `many` is not `many1`). [This commit](https://github.com/Dr-Nekoma/spatula/commit/c7cd8cae5223fe371168a19b9f40c9c62e233918) fixes that.
